[project]
name = "qrmaker"
version = "0.1.0"
description = "Simple qrcode Generator"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pillow>=12.3.0",
    "qrcode>=8.2",
    "ttkbootstrap>=2.0.1",
]

[tool.ruff.lint]
extend-select = [
    "I",    # isort (schon da)
    "E",    # pycodestyle errors
    "W",    # pycodestyle warnings
    "F",    # pyflakes (unused imports, etc.)
    "B",    # flake8-bugbear (häufige Bugs/Fallstricke)
    "UP",   # pyupgrade (moderne Syntax-Vorschläge)
    "SIM",  # flake8-simplify
    "D",    # Docstye checks
]

[tool.pytest.ini_options]
pythonpath = ["."]
testpaths = ["tests"]

[dependency-groups]
dev = [
    "codespell>=2.4.3",
    "mypy>=2.3.0",
    "pre-commit>=4.6.1",
    "pytest>=9.1.1", # Python test suite.
    "pytest-cov>=7.1.0", # allowes to see what portions of code actually get tested.
    "types-qrcode>=8.2.0.20260518",
]
